services:
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: HealthCare-app
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/healthcare?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATA_REDIS_URL=redis://redis:6379
      - SPRING_DATA_REDIS_SSL=false
      - SPRING_CACHE_TYPE=redis
      - JWT_SECRET=MaCleSecreteSuperLongueEtSecurisee1234567890!
      - JWT_EXPIRATION=86400000
    depends_on:
      - redis
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: HealthCare-db
    restart: always
    environment:
      - MYSQL_DATABASE=healthcare
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: HealthCare-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  redisinsight:
    image: redis/redisinsight:latest
    container_name: HealthCare-redisinsight
    restart: always
    ports:
      - "8001:8001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: