spring.application.name=HealthCare

# 1. Darouria bash l-cloud i-3tiha l-port dynamic dialo!
server.port=${PORT:8080}

# 2. Les variables dial l-DB khasshoum i-kouno dynamic
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Cache & Redis f l-cloud
# (?? Ila ma-3ndekch container Redis f l-cloud, red SPRING_CACHE_TYPE=simple f l-dashboard)
spring.cache.type=${SPRING_CACHE_TYPE:simple}
spring.data.redis.url=${SPRING_DATA_REDIS_URL:}
spring.data.redis.ssl.enabled=${SPRING_DATA_REDIS_SSL:false}

# 4. JWT Configuration
jwt.secret=${JWT_SECRET:MaCleSecreteSuperLongueEtSecurisee1234567890!}
jwt.expiration=${JWT_EXPIRATION:86400000}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true